config/routes.rb
Rails.application.routes.draw do

  # Something worth noting:
  # In Rails Engines, last time I checked (which was Rails 3.0.3), you can't
  # use namespaces in a route file within an engine.  It doesn't seem like
  # that's what you'll be doing here, but I thought I'd let you know.

  resources :ribbons
  resources :collections
end
 

app/models/business.rb
require "#{TrizleClient.models_dir}/business"
class Business
  has_many :business_ribbons
  has_many :ribbons, :through => :business_ribbons
  has_many :fans, :dependent => :destroy




  has_many :quest_rewards, :dependent => :destroy

  def next_quest
    return Quest.first if quest_rewards.empty?

    # find the last quest rewarded
    furthest_quest = quest_rewards.find(:last, :order => "quest_id")

    # find any quest before the furthest one that's incomplete
    # (e.g. business might complete the 4th quest, but hasn't completed the 3rd one)
    quests_completed_before_furthest_quest_rewarded = Quest.find(:all, :conditions => ["id < ?", furthest_quest.quest_id]).reject{|q|quest_rewards.collect(&:quest_id).include?(q.id)}
    if quests_completed_before_furthest_quest_rewarded.empty?
      return Quest.where(["id > ?", furthest_quest.quest_id]).first
    else
      return quests_completed_before_furthest_quest_rewarded.first
    end
  rescue
    return Quest.last
  end

  def next_quest_surprise_offer_ends_at
    if quest_rewards.empty?
      created_at + next_quest.hours_given_to_complete_for_surprise.hours
    else
      quest_rewards.order("created_at").last.created_at + next_quest.hours_given_to_complete_for_surprise.hours
    end
  end

  def seconds_until_next_quest_surprise_offer_ends
    t = next_quest_surprise_offer_ends_at - Time.now
    t = 0 if Time.now > next_quest_surprise_offer_ends_at
    return t.to_i
  end

  def next_quest_surprise_offer_available?
    seconds_until_next_quest_surprise_offer_ends > 0
  end

end

app/models/business_ribbon.rb
class BusinessRibbon < ActiveRecord::Base
##  acts_as_audited
  belongs_to :business
  belongs_to :ribbon

  def name
    ribbon.name
  end

  after_create :after_create_tasks
  def after_create_tasks
    business.notifications(:title => "You've achieved the ribbon #{name}.")
  end




##  ## REDIS - NEWS FEED
##  include RedisMethods
##  def push_to_followers
##    # this pushes the notification to all people who are following this entry (to their unique feeds)
##    push_to_followers_of(business.user)
##    push_to_followers_of(business)
##  end
##  ######################
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  
  validates_uniqueness_of :name
  has_many :ribbons
end

app/models/fan.rb
class Fan < ActiveRecord::Base
  
end

app/models/ribbon.rb
class Ribbon < ActiveRecord::Base
  validates_uniqueness_of :name
  validates_presence_of :points
  default_scope :order => "points"
  belongs_to :collection

  scope :level, :conditions => "level is true"
  scope :regular, :conditions => "level is not true"

  has_attached_file :image,
    :styles => {
    :thumb => "64x64",
    :gallery => "200x200",
    :medium => "300x300"
  },
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => "#{self.to_s.tableize}/:attachment/:id/ribbons/:style.:extension"

  has_attached_file :large_image,
    :styles => {
    :thumb => "64x64",
    :gallery => "200x200",
    :medium => "300x300"
  },
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => "#{self.to_s.tableize}/:attachment/:id/ribbons/:style.:extension"

  has_many :comments, :as => :commentable

  def self.last_awarded
    self.last
  end

  def collection_name
    collection.name
  rescue
    nil
  end

  def self.have?(identity)
    self.all.collect(&:identity).include?(identity)
  end

  has_many :users, :dependent => :destroy
  has_many :users, :through => :business_ribbons

  def generate_image
    letters = %w{a b c d e f g h i j k l m n o p q r s t u v w x y z}
    random_letter = letters.shuffle.first
    img = Magick::Image.read("#{RAILS_ROOT}/public/ribbons/layouts/#{rand(2) + 1}.png").first

    # Colorize to change colors of ribbon
    colorized = img.modulate(1,1 + (rand(6) / 10.to_f),1 + (rand(6) / 10.to_f))

    # first add a transaprent image so yuo can place the symbol on top (then resize it to fit demensions)
    symbol_image_canvas = Magick::Image.read("#{RAILS_ROOT}/public/ribbons/transparent.png").first
    symbol_image_canvas.background_color = "none"
    gc = Magick::Draw.new
    gc.align = Magick::CenterAlign
    gc.pointsize = 290
    # set the symbol color to equal the badge's border color!
    gc.fill = colorized.pixel_color(50,50)

    # randomly add white to the symbols!
    gc.fill = 'white' if rand(5) == 3
    gc.font = "/#{RAILS_ROOT}/public/ribbons/dingbats/artefekt.ttf"
    gc.annotate(symbol_image_canvas, 0, 0, 240, 320, random_letter)
    symbol_image_canvas.resize_to_fit!(340,390)

    result = colorized.composite(symbol_image_canvas, Magick::CenterGravity, Magick::OverCompositeOp)

    path_to_image_in_tmp_directory = "#{Rails.root}/tmp/ribbon-#{id}.png"
    result.write(path_to_image_in_tmp_directory)

    self.image = File.open(path_to_image_in_tmp_directory, "r")
    self.save
  end
end

app/controllers/ribbons_controller.rb
class RibbonsController < ApplicationController
  # require_role "admin", :for => [:new, :create, :update, :destroy]
  # GET /ribbons
  # GET /ribbons.xml
  def index
    ribbons = Ribbon
    ribbons.where("level is not true")
    ribbons.where("level is true") if params[:level] == "true"
    @ribbons = ribbons.order("name").paginate(:page => params[:page], :per_page => 25)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ribbons }
    end
  end

  # GET /ribbons/1
  # GET /ribbons/1.xml
  def show
    @ribbon = Ribbon.find(params[:id])
   @commentable = @ribbon
    @comments = @commentable.comments

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ribbon }
    end
  end

  # GET /ribbons/new
  # GET /ribbons/new.xml
  def new
    @ribbon = Ribbon.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ribbon }
    end
  end

  # GET /ribbons/1/edit
  def edit
    @ribbon = Ribbon.find(params[:id])
  end

  # POST /ribbons
  # POST /ribbons.xml
  def create
    @ribbon = Ribbon.new(params[:ribbon])

    respond_to do |format|
      if @ribbon.save
        flash[:notice] = 'Ribbon was successfully created.'
        format.html { redirect_to(@ribbon) }
        format.xml  { render :xml => @ribbon, :status => :created, :location => @ribbon }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ribbon.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ribbons/1
  # PUT /ribbons/1.xml
  def update
    @ribbon = Ribbon.find(params[:id])

    respond_to do |format|
      if @ribbon.update_attributes(params[:ribbon])
        flash[:notice] = 'Ribbon was successfully updated.'
        format.html { redirect_to(@ribbon) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ribbon.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ribbons/1
  # DELETE /ribbons/1.xml
  def destroy
    @ribbon = Ribbon.find(params[:id])
    @ribbon.destroy

    respond_to do |format|
      format.html { redirect_to(ribbons_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/trizle_misc_helper.rb
# everything below is available in controllers too! (see lib/trizle_client.rb)
module TrizleMiscHelper

end

app/views/ribbons/_form.html.erb
<%= semantic_form_for(@ribbon, :html => { :multipart => true }) do |f| %>
  <%= f.error_messages %>

  <%= f.inputs do %>
  
    
    <%= f.input :name %>
  
  
    
    <%= f.input :points %>
  
  

    <%= f.input :description %>

    <li>
      <%= f.label :collection_id %>
    <%= f.collection_select :collection_id, Collection.all, :id, :name %>
    </li>


<%= li_file_field(f, :image) %>
<%= li_file_field(f, :large_image) %>
  
  
    <%= f.buttons %>
<% end %>
  
<% end %>

app/views/ribbons/_sidebar.html.erb
<% content_for :sidebar do %>
  <div class="content">

    <h3>Collections</h3>
  <ul class="nav">
      <li><%= link_to_unless_current "View collections", collections_path %></li>
  </ul>
    <h3>Ribbons</h3>
    <ul class="nav">
      <li><%= link_to_unless_current "Ribbons", "/trizle/ribbons?level=false" %></li>
      <li><%= link_to_unless_current "Level ribbons", "/trizle/ribbons?level=true" %></li>
    </ul>

      <%#= render "trizle_sections/partials/achievements_nav" %>

  </div>
<% end %>

app/views/ribbons/_sidebar_list.html.erb
<h3><%= pluralize ribbons.length, "Ribbon" %></h3>
<div class="thumb_list">
<ul class="thumbs">
  <% for ribbon in ribbons[0..19] %>
  <li><%= photo(ribbon.image, "utility") %></li>
  <% end %>
</ul>
<%= clear %>
</div>

app/views/ribbons/edit.html.erb
<h1>Edit</h1>


<%= render "form" %>

<%= link_to 'Show', @ribbon %> |
<%= link_to 'Back', ribbons_path %>

app/views/ribbons/index.html.erb
<div class="content with_sidebar">



<div class="boost_headline">
  <%#= cartoon("cartoon21.png", :class => "") %>
  <div class="boost_content">
    <% cache("ribbons-size", :expires_in => 1.week) do %>
    <h4>Collect All <%= pluralize Ribbon.all.size, "Ribbon" %></h4>
    <% end %>
    <span>
      You have <%= raw link_to(pluralize(current_business.ribbons.size, "ribbon"), ribbons_path) %>. See what quests you can do and other ways to get points to get ribbons. Here's a sampling of things you can do.
    </span>
  </div>
  <%= clear %>
</div>
<div class="boost_section top bottom">
  <%#= cartoon("cartoon21.png", :class => "") %>
  <div class="boost_content">
    <h4>See your ribbons</h4>
    Pixel perfect design & finely tuned development combined with efficient processes are foundational elements in each and every project I take on. View Recent Projects
    <ol>
    <% @ribbons.each do |ribbon| %>
      <li>
        <%= link_to ribbon.name, ribbon, :class => "title" %>
        <%= " · You have this!" if current_business.business_ribbons.collect(&:ribbon_id).include?(ribbon.id) %>
      </li>
    <% end %>
  </ol>
  </div>
  <%= clear %>
</div>




</div>


<%= render "ribbons/sidebar" %>

app/views/ribbons/new.html.erb
<div class="content">
<h1>New ribbon</h1>
<%= render "form" %>

<%= link_to 'Back', ribbons_path %>
</div>

app/views/ribbons/show.html.erb
<div class="content with_sidebar">

  <h1>
     <%=h @ribbon.name %> Ribbon
  </h1>


<p>
  <b>Points:</b>
  <%=h @ribbon.points %>
</p>

<p>
  <b>Description:</b>
  <%=h @ribbon.description %>
</p>


</div>


<% content_for :sidebar do %>

  <% unless @ribbon.level? %>
  <h3>Collection</h3>
  <%#= link_to @ribbon.collection_name, collection_path(:id => @ribbon.collection_name) %>
  <% end %>

<% end %>